title: Mike Casey
description: Entrepreneur seeking the good life
url: "https://mcasey.xyz"
email: hello@caseyjr.org
copyright: "© 2024 Mike Casey"

# Build settings
theme: minima
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

paginate: 50
paginate_path: "/page:num/"

collections:
  recommendations:
    output: true
    permalink: /recommendations/:path/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/posts/:year/:month/:day/:title/"

header_pages:
  - publications.md
  - recommended-reading.md